server:
  port: 8080

spring:
  application:
    name: skif-monitor

epics:
  simulation-mode: false
  ca-addr-list: ""
  pv:
    linac:
      klystron1-power: "RF-LN:KL1-DiPwrWf:Mea"
      klystron2-power: "RF-LN:KL2-DiPwrWf:Mea"
      klystron3-power: "RF-LN:KL3-DiPwrWf:Mea"
      klystron1-phase: "RF-LN:KL1-DiPhsWf:Mea"
      klystron2-phase: "RF-LN:KL2-DiPhsWf:Mea"
      klystron3-phase: "RF-LN:KL3-DiPhsWf:Mea"
      klystron1-status: "RF-LN:KL1:LLRF-PwrOn:Sts"
      klystron2-status: "RF-LN:KL2:LLRF-PwrOn:Sts"
      klystron3-status: "RF-LN:KL3:LLRF-PwrOn:Sts"
      gun-current: ""
      linac-current: ""
      rf-status: ""
      injector-status: ""
      systems-status: ""
      kl1-llrf-power-status: "RF-LN:KL1:LLRF-PwrOn:Sts"
      kl2-llrf-power-status: "RF-LN:KL2:LLRF-PwrOn:Sts"
      kl3-llrf-power-status: "RF-LN:KL3:LLRF-PwrOn:Sts"
      kl1-pwr-ilk-status: "RF-LN:KL1-PwrILK:Sts"
      kl2-pwr-ilk-status: "RF-LN:KL2-PwrILK:Sts"
      kl3-pwr-ilk-status: "RF-LN:KL3-PwrILK:Sts"
    booster:
      bd1: "MG-BR:BD1-I:Wf"
      bd2: "MG-BR:BD2-I:Wf"
      bf: "MG-BR:BF-I:Wf"
      beam-current: "BI-BDS:DCCT-Ch1Wf10Data:Mes"
      cav1-voltage: "RF-BR:CAV1:LLRF-CavityVoltageWf:Mea"
      cav2-voltage: "RF-BR:CAV2:LLRF-CavityVoltageWf:Mea"
      cav3-voltage: "RF-BR:CAV3:LLRF-CavityVoltageWf:Mea"
      rf-status: "BOOSTER:RF:STATUS"
      magnet-status: "BOOSTER:MAG:STATUS"
      cav1-llrf-modulator-status: "RF-BR:CAV1:LLRF-ModulatorOn:Sts"
      cav2-llrf-modulator-status: "RF-BR:CAV2:LLRF-ModulatorOn:Sts"
      cav3-llrf-modulator-status: "RF-BR:CAV3:LLRF-ModulatorOn:Sts"
      bd1-pson-status: "MG-BR:BD1-PSON:Cmd"
      bd2-pson-status: "MG-BR:BD2-PSON:Cmd"
      bf-pson-status: "MG-BR:BF-PSON:Cmd"

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    ru.skif: DEBUG
  file:
    name: skif-monitor.log
